services:
  vault:
    image: hashicorp/vault:1.15.4
    container_name: hashicorp-vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: server -dev -dev-kv-v1

  vault-setup:
    image: hashicorp/vault:1.15.4
    container_name: vault-setup
    volumes:
      - ./setup.sh:/setup.sh
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root-token"
    entrypoint: sh /setup.sh
    depends_on:
      - vault
