version: "3.8"

services:
  vault:
    image: hashicorp/vault:1.15.4
    container_name: hashicorp-vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root-token"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
      VAULT_LOG_LEVEL: "debug"
    volumes:
      - ./vault/config:/vault/config
      - ./vault/logs:/vault/logs
      - ./vault/data:/vault/data
      - ./vault/scripts:/vault/scripts
    entrypoint: ["/bin/sh", "/vault/scripts/startup.sh"]
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--spider",
          "--quiet",
          "http://127.0.0.1:8200/v1/sys/health",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - vault-network

  vault-initializer:
    image: hashicorp/vault:1.15.4
    container_name: vault-initializer
    depends_on:
      vault:
        condition: service_healthy
    volumes:
      - ./vault/scripts:/vault/scripts
      - ./vault/credentials:/vault/credentials
    environment:
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "root-token"
    entrypoint: ["/bin/sh", "/vault/scripts/initialize.sh"]
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge
